[project]
name = "frontend"
version = "0.1.0"
description = "SmartCity Explorer â€” Interface Streamlit"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.30",
    "httpx>=0.26",
    "plotly>=5.18",
    "pandas>=2.1",
    "shared",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/frontend"]
